# Generated by Django 5.2.5 on 2026-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('client', 'Client'), ('developer', 'Developer'), ('student', 'Student')], default='developer', max_length=20),
        ),
    ]
