# Generated by Django 5.2.5 on 2026-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
