# Generated by Django 5.2.5 on 2026-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=2),
        ),
    ]
