# Generated by Django 5.2.5 on 2026-06-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitealert',
            options={'ordering': ['-created_on'], 'verbose_name': 'Site Alert', 'verbose_name_plural': 'Site Alerts'},
        ),
        migrations.AddField(
            model_name='sitealert',
            name='title',
            field=models.CharField(default='Site Alert', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitealert',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
